table Calendario
	lineageTag: ea0191fe-159d-4731-9887-661bfc131a6f

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a924a57b-9b64-4e51-8acf-4ec2b6931c4f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: e04bba84-d06e-4c82-a5aa-70be8cd293a5
			defaultHierarchy: LocalDateTable_82b66e6d-1be2-4ea8-a836-981763acc28b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 152675cc-1191-49ed-a92c-d8f5389f0e88
		summarizeBy: max
		sourceColumn: Año

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

	column TrimNum
		dataType: int64
		formatString: 0
		lineageTag: ffddad5a-2e8d-4f01-b86a-67869eab4baa
		summarizeBy: sum
		sourceColumn: TrimNum

		annotation SummarizationSetBy = Automatic

	column TrimNom
		dataType: string
		lineageTag: e2282c25-8529-4223-a4ff-ad87813304c9
		summarizeBy: none
		sourceColumn: TrimNom

		annotation SummarizationSetBy = Automatic

	column MesNum
		dataType: int64
		formatString: 0
		lineageTag: 57cb42ce-9c2a-4967-a5bc-0433d549f025
		summarizeBy: sum
		sourceColumn: MesNum

		annotation SummarizationSetBy = Automatic

	column MesNom
		dataType: string
		lineageTag: fbe897ab-87b6-4931-9309-0d2ece822a05
		summarizeBy: none
		sourceColumn: MesNom

		annotation SummarizationSetBy = Automatic

	column MesNomAB
		dataType: string
		lineageTag: f8d61238-67f0-4fb7-99e8-bbb09c4f55af
		summarizeBy: none
		sourceColumn: MesNomAB

		annotation SummarizationSetBy = Automatic

	column SemNrmNum
		dataType: int64
		formatString: 0
		lineageTag: 264b57c0-2b28-4729-b62e-fa91157b2811
		summarizeBy: sum
		sourceColumn: SemNrmNum

		annotation SummarizationSetBy = Automatic

	column DiaNum
		dataType: int64
		formatString: 0
		lineageTag: a600b7c7-8d57-44e4-bb18-8d18b70ef1df
		summarizeBy: sum
		sourceColumn: DiaNum

		annotation SummarizationSetBy = Automatic

	column DiaNom
		dataType: string
		lineageTag: 785ee4dc-85fc-465a-9793-029eb77d035d
		summarizeBy: none
		sourceColumn: DiaNom

		annotation SummarizationSetBy = Automatic

	column DiaNomAB
		dataType: string
		lineageTag: 3ff93eb3-2b4f-48aa-b9eb-24d09f63fe9e
		summarizeBy: none
		sourceColumn: DiaNomAB

		annotation SummarizationSetBy = Automatic

	column MesCalendario
		dataType: int64
		formatString: 0
		lineageTag: ce309cdd-c0c6-42f4-9441-8b2b4126bcd5
		summarizeBy: sum
		sourceColumn: MesCalendario

		annotation SummarizationSetBy = Automatic

	column DiaSemNum
		dataType: string
		lineageTag: 718766ab-a6bb-4be7-a50b-4536a96af662
		summarizeBy: none
		sourceColumn: DiaSemNum

		annotation SummarizationSetBy = Automatic

	column MesAño
		dataType: string
		lineageTag: ab0b1b69-9643-4d9e-b918-ad857488d4df
		summarizeBy: none
		sourceColumn: MesAño

		annotation SummarizationSetBy = Automatic

	column FiltroActual
		dataType: string
		lineageTag: 83f91226-2cd2-4aa0-9344-3678e1816c36
		summarizeBy: none
		sourceColumn: FiltroActual

		annotation SummarizationSetBy = Automatic

	column FiltroActual_MA
		dataType: string
		lineageTag: 7063e04d-4799-441d-9b44-ba8726c2cf96
		summarizeBy: none
		sourceColumn: FiltroActual_MA

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source = ```
				let
				    Origen = #"StartDate",
				    #"Convertida en tabla" = #table(1, {{Origen}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Convertida en tabla",{{"Column1", "StartDate"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "EndDate", each Date.From(DateTime.LocalNow ())),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "Dates", each {Number.From([StartDate])..Number.From([EndDate])}),
				    Dates = #"Personalizada agregada1"{0}[Dates],
				    #"Convertida en tabla1" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Convertida en tabla1",{{"Column1", "DateKey"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"DateKey", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Año", each Date.Year([DateKey])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Año", Int64.Type}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "TrimNum", each Date.QuarterOfYear([DateKey])),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"TrimNum", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "TrimNom", each "Trim " & Number.ToText(Date.QuarterOfYear([DateKey]))),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "MesNum", each Date.Month([DateKey])),
				    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "MesNom", each Text.Proper(Date.MonthName([DateKey],"es-ES"))),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom4",{{"MesNum", Int64.Type}}),
				    #"Added Custom5" = Table.AddColumn(#"Changed Type3", "MesNomAB", each Text.Start(Text.Proper(Date.MonthName([DateKey],"es-ES")),3)),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom5",{{"MesNomAB", type text}}),
				    #"Added Custom6" = Table.AddColumn(#"Changed Type4", "SemNrmNum", each Date.WeekOfYear([DateKey],1)),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom6",{{"SemNrmNum", Int64.Type}}),
				    #"Added Custom8" = Table.AddColumn(#"Changed Type5", "DiaNum", each Date.Day([DateKey])),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Added Custom8",{{"DiaNum", Int64.Type}}),
				    #"Added Custom9" = Table.AddColumn(#"Changed Type7", "DiaNom", each Text.Proper(Date.DayOfWeekName([DateKey], "eS-ES"))),
				    #"Added Custom10" = Table.AddColumn(#"Added Custom9", "DiaNomAB", each Text.Start(Text.Proper(Date.DayOfWeekName([DateKey], "eS-ES")),3)),
				    #"Added Custom11" = Table.AddColumn(#"Added Custom10", "AñoMes", each Number.ToText([Año])&"-"& [MesNomAB]),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Added Custom11",{{"AñoMes", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type8",{"AñoMes"}),
				    #"Added Custom12" = Table.AddColumn(#"Removed Columns", "MesP", each Date.ToText([DateKey], "MMM", "es-419")),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom12",{"MesP"}),
				    #"Added Custom13" = Table.AddColumn(#"Removed Columns1", "Custom", each Number.ToText([Año])&Text.PadStart(Number.ToText([MesNum]),2,"0")),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom13",{{"Custom", "MesCalendario"}}),
				    #"Added Custom14" = Table.AddColumn(#"Renamed Columns1", "DiaSemNum", each Date.DayOfWeek([DateKey],Day.Monday)),
				    #"Added Custom15" = Table.AddColumn(#"Added Custom14", "Custom", each Number.ToText([Año])&"-"&[MesNomAB]),
				    #"Texto en mayúsculas" = Table.TransformColumns(#"Added Custom15",{{"Custom", Text.Upper, type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Texto en mayúsculas",{{"Custom", "YM"}, {"DateKey", "Date"}}),
				    #"Personalizada agregada2" = Table.AddColumn(#"Renamed Columns2", "fecha_curso", each DateTimeZone.UtcNow ()),
				    #"Mes insertado" = Table.AddColumn(#"Personalizada agregada2", "mes_curso", each Date.Month([fecha_curso]), Int64.Type),
				    #"Año insertado" = Table.AddColumn(#"Mes insertado", "año_curso", each Date.Year([fecha_curso]), Int64.Type),
				    #"Personalizada agregada3" = Table.AddColumn(#"Año insertado", "año_mes_curso", each Number.ToText([año_curso])&Text.PadStart(Number.ToText([mes_curso]),2,"0")),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Personalizada agregada3",{{"año_mes_curso", Int64.Type}, {"MesCalendario", Int64.Type}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado", "filtro_general", each 
				if [MesCalendario] = [año_mes_curso] then "Mes en curso" else
				if [MesCalendario] = [año_mes_curso]-1 then "Mes anterior" else
				if [MesCalendario] = [año_mes_curso]-2 then "Hace 2 Meses" else
				if [MesCalendario] = [año_mes_curso]-3 then "Hace 3 Meses" else
				if [MesCalendario] = [año_mes_curso]-4 then "Hace 4 Meses" else
				if [MesCalendario] = [año_mes_curso]-5 then "Hace 5 Meses" else
				if [MesCalendario] = [año_mes_curso]-6 then "Hace 6 Meses" else "Mayor a 6 Meses"),
				    #"Personalizada agregada4" = Table.AddColumn(#"Columna condicional agregada", "Mes Año", each if Date.Month([Date]) = Date.Month(DateTime.LocalNow()) and Date.Year([Date]) = Date.Year(DateTime.LocalNow()) then "Mes En Curso" else [YM]),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Personalizada agregada4",{"fecha_curso", "mes_curso", "año_curso", "año_mes_curso"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas quitadas",{{"Mes Año", "FiltroActual_MA"}, {"filtro_general", "FiltroActual"}, {"YM", "MesAño"}})
				in
				    #"Columnas con nombre cambiado1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

