table Peliculas
	lineageTag: 5d45bb68-dbfa-4070-bf34-dc1344e7951d

	column Id_Pelicula
		dataType: int64
		formatString: 0
		lineageTag: afe118cc-f3df-4dde-9159-bbc578dfa92f
		summarizeBy: none
		sourceColumn: Id_Pelicula

		annotation SummarizationSetBy = Automatic

	column 'Nombre Pelicula'
		dataType: string
		lineageTag: 69a057ed-4bbb-474b-a605-7177f0a1caca
		summarizeBy: none
		sourceColumn: Nombre Pelicula

		annotation SummarizationSetBy = Automatic

	column 'Nombre Género'
		dataType: string
		lineageTag: 69f69c8a-d626-45dc-b9fd-f1af86749c52
		summarizeBy: none
		sourceColumn: Nombre Género

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: f9825bad-e882-40d8-bfe0-9455c0e75d97
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Protagonistas
		dataType: string
		lineageTag: 24d7c1b5-f723-48d7-ad62-b2f9f9c69e1f
		summarizeBy: none
		sourceColumn: Protagonistas

		annotation SummarizationSetBy = Automatic

	column Director
		dataType: string
		lineageTag: 07fde59f-8ac8-4059-945e-5157c8c46fe3
		summarizeBy: none
		sourceColumn: Director

		annotation SummarizationSetBy = Automatic

	column Id_Genero = LOOKUPVALUE(Datos[Id_Género], Datos[Id_Pelicula], Peliculas[Id_Pelicula])
		formatString: 0
		lineageTag: 2e84f74a-dcf4-4e7e-9d22-36705e8f0fca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Peliculas = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:\Users\HR453WU\OneDrive - EY\Documents\GitHub\prueba-tecnica-analista-datos-pbi\data"),
				    #"C:\Users\HR453WU\OneDrive - EY\Documents\GitHub\prueba-tecnica-analista-datos-pbi\data\_DimPeliculas xlsx" = Origen{[#"Folder Path"="C:\Users\HR453WU\OneDrive - EY\Documents\GitHub\prueba-tecnica-analista-datos-pbi\data\",Name="DimPeliculas.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"C:\Users\HR453WU\OneDrive - EY\Documents\GitHub\prueba-tecnica-analista-datos-pbi\data\_DimPeliculas xlsx"),
				    Peliculas_Sheet = #"Imported Excel Workbook"{[Item="Peliculas",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Peliculas_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Id_Pelicula", Int64.Type}, {"Nombre Pelicula", type text}, {"Nombre Género", type text}, {"Año", Int64.Type}, {"Protagonistas", type text}, {"Director", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

